rinkimai/urls.py
from django.contrib import admin
from django.urls import path

from rinkimai.views import add_group
from rinkimai.views import add_person
from rinkimai.views import add_quote
from rinkimai.views import approve_quote
from rinkimai.views import group_quotes
from rinkimai.views import person_quotes
from rinkimai.views import index
from rinkimai.views import quote_details
from rinkimai.views import reactions
from rinkimai.views import save_reaction
from rinkimai.views import tag_quotes
from rinkimai.views import unapproved_quotes
from rinkimai.views import voter_candidates

urlpatterns = [
    path('', index, name='home'),
    path('add-quote', add_quote, name="add-quote"),
    path('add-person', add_person, name='add-person'),
    path('add-group', add_group, name='add-group'),
    path('save-reaction', save_reaction, name='save-reaction'),
    path('approve-quote', approve_quote, name='approve-quote'),
    path('unapproved-quotes', unapproved_quotes, name='unapproved-quotes'),
    path('reactions', reactions, name="my-reactions"),
    path('my-candidates', voter_candidates, name="my-candidates"),
    path('quote/<int:quote_id>', quote_details, name='quote-details'),
    path('person/<str:slug>', person_quotes, name='person-quotes'),
    path('group/<str:slug>', group_quotes, name='group-quotes'),
    path('tag/<str:tag>', tag_quotes, name='tag-quotes'),
    path('valdymas/', admin.site.urls),
]

rinkimai/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Group(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=255)
    abbr = models.CharField(max_length=16)
    aliases = ArrayField(models.CharField(max_length=255), blank=True, default=list)

    def __str__(self):
        return self.abbr or self.name

    def get_absolute_url(self):
        return reverse('group-quotes', args=[self.slug])


class Person(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=255)
    bday = models.DateField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    aliases = ArrayField(models.CharField(max_length=255), blank=True, default=list)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('person-quotes', args=[self.slug])


class Election(models.Model):

    class Kind(models.TextChoices):
        PRESIDENT = 'president', _("President")
        PARLIAMENT = 'parliament', _("Parliament")

    date = models.DateField(null=True)
    kind = models.CharField(max_length=40, choices=Kind.choices, null=True)

    def __str__(self):
        return self.date.isoformat() + f' ({self.kind})'


class Candidate(models.Model):

    class Kind(models.TextChoices):
        VIENMANDATE = 'vienmandate', _("Vienmandatė")
        DAUGIAMANDATE = 'daugiamandate', _("Daugiamandatė")

    class Meta:
        unique_together = [
            ['election', 'person', 'group'],
        ]

    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    kind = models.CharField(max_length=40, choices=Kind.choices, null=True, blank=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True, blank=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True)
    number = models.PositiveSmallIntegerField(null=True, blank=True)
    name = models.CharField(max_length=255)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    private_key = models.CharField(max_length=40)
    quote = models.ForeignKey('self', related_name='parent', null=True, blank=True, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, null=True, blank=True, on_delete=models.CASCADE)
    source = models.URLField()
    date = models.DateField(null=True)
    text = models.TextField()
    image = models.ImageField(null=True, blank=True)
    tags = ArrayField(models.CharField(max_length=40), blank=True, default=list)
    reaction = models.SmallIntegerField(null=True, blank=True)
    active = models.BooleanField(default=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    approved_by = models.ForeignKey(User, null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('quote-details', args=[str(self.pk)])


class Reaction(models.Model):
    private_key = models.CharField(max_length=40)
    public_key = models.CharField(max_length=40)
    quote = models.ForeignKey(Quote, related_name='reactions', on_delete=models.CASCADE)
    reaction = models.SmallIntegerField(default=0, blank=True)
    tags = ArrayField(models.CharField(max_length=40), blank=True, default=list)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [
            ['private_key', 'quote'],
        ]


class Moderator(models.Model):
    name = models.CharField(max_length=255)
    public_key = models.CharField(max_length=40)
    active = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return f"{self.name} ({self.public_key})"


class Settings(models.Model):
    election = models.OneToOneField(Election, on_delete=models.CASCADE, null=True, blank=True)

rinkimai/forms.py
from django import forms
from django.forms import Form
from django.forms.models import ModelForm

from rinkimai.models import Group
from rinkimai.models import Person
from rinkimai.models import Quote
from rinkimai.models import Reaction


class SaveReactionForm(ModelForm):

    class Meta:
        model = Reaction
        fields = [
            'quote',
            'reaction',
        ]


class AskQuoteSourceForm(Form):

    source = forms.URLField()


class AddQuoteForm(ModelForm):

    class Meta:
        model = Quote
        fields = [
            'source',
            'person',
            'group',
            'date',
            'text',
            'tags',
        ]


class PersonForm(ModelForm):

    class Meta:
        model = Person
        fields = [
            'name',
            'bday',
        ]


class GroupForm(ModelForm):

    class Meta:
        model = Group
        fields = [
            'name',
            'abbr',
        ]


class ApproveQuoteForm(ModelForm):

    class Meta:
        model = Quote
        fields = [
            'active',
        ]

rinkimai/views.py
from typing import List
from typing import Optional
from urllib.parse import urlencode

from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http.request import HttpRequest
from django.http.response import Http404
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.text import slugify
from django.views.decorators.http import require_http_methods

from rinkimai.forms import AddQuoteForm
from rinkimai.forms import ApproveQuoteForm
from rinkimai.forms import AskQuoteSourceForm
from rinkimai.forms import GroupForm
from rinkimai.forms import PersonForm
from rinkimai.forms import SaveReactionForm
from rinkimai.helpers import extract_source_data
from rinkimai.helpers import suggested_person_or_group_for_quote
from rinkimai.models import Group
from rinkimai.models import Person
from rinkimai.models import Quote
from rinkimai.models import Reaction
from rinkimai.services import get_current_election
from rinkimai.services import query_quotes
from rinkimai.services import query_voter_quotes
from rinkimai.utils.dates import normalize_date
from rinkimai.utils.voter import Voter
from rinkimai.services import query_voter_candidates


def index(request: HttpRequest):
    voter: Voter = request.voter
    election = get_current_election()
    return TemplateResponse(request, 'index.html', {
        'voter': voter,
        'quotes': query_quotes(election, voter, user=request.user),
        'active_menu_item': 'home',
        'add_new_quote_url': reverse('add-quote'),
    })


@require_http_methods(['POST'])
def save_reaction(request: HttpRequest):
    voter: Voter = request.voter
    try:
        reaction = Reaction.objects.get(
            private_key=voter.private_key,
            quote=request.POST.get('quote'),
        )
    except ObjectDoesNotExist:
        reaction = None
    form = SaveReactionForm(request.POST, instance=reaction)
    if form.is_valid():
        reaction = form.save(commit=False)
        reaction.private_key = voter.private_key
        reaction.public_key = voter.public_key
        reaction.save()
        return JsonResponse({'errors': None})
    else:
        return JsonResponse({'errors': form.errors.get_json_data()})


def reactions(request: HttpRequest):
    voter: Voter = request.voter
    return TemplateResponse(request, 'reactions.html', {
        'voter': voter,
        'quotes': query_voter_quotes(voter),
        'active_menu_item': 'my-reactions',
        'add_new_quote_url': reverse('add-quote'),
    })


@require_http_methods(['GET', 'POST'])
def add_quote(request: HttpRequest):
    if request.method == 'GET':
        source = request.GET.get('source')
        person = request.GET.get('person')
        group = request.GET.get('group')
        if source is None:
            form = AskQuoteSourceForm()
            return TemplateResponse(request, 'ask_quote_source.html', {
                'form': form,
                'person': person,
                'group': group,
            })
        else:
            data = extract_source_data(source)
            names = data['names']
            if person:
                names += [person]
            if group:
                names += [group]
            names = suggested_person_or_group_for_quote(names)
            form = AddQuoteForm(initial={
                'source': source,
                'date': data['date'],
            })
            return TemplateResponse(request, 'add_quote.html', {
                'form': form,
                'names': names,
                'source': source,
            })
    else:
        post = request.POST.copy()

        if post['date']:
            post['date'] = normalize_date(post['date'])

        author = post.get('suggested_author', '')
        if ':' in author:
            author_type, author = author.split(':', 1)
            if author_type == 'person':
                person = author
                group = ''
            else:
                person = ''
                group = author
        else:
            author_type = author
            person = ''
            group = ''

        if author_type == 'person':
            post['person'] = person = person or post.get('person', '')
            post['group'] = group = ''
        else:
            post['person'] = person = ''
            post['group'] = group = group or post.get('group', '')

        if person.isdigit():
            person = ''
        elif person:
            found: List[Person] = list(
                Person.objects.
                only('pk', 'name').
                filter(Q(name=person) | Q(aliases__contains=[person]))
            )

            # If one person found, just set id of that person.
            if len(found) == 1:
                post['person'] = found[0].pk

            # If more than one person found, return back to form and ask to
            # select which person.
            elif len(found) > 1:
                names = [p.name for p in found]
                names = suggested_person_or_group_for_quote(names)
                form = AddQuoteForm(post)
                return TemplateResponse(request, 'add_quote.html', {
                    'form': form,
                    'names': names,
                    'source': post.get('source'),
                })

            # If person is not found, save Quote and proceed to the next Add
            # Person form.
            else:
                post['person'] = ''

        if group.isdigit():
            group = ''
        elif group:
            found: List[Group] = list(
                Group.objects.
                only('pk', 'name').
                filter(
                    Q(name__icontains=group) |
                    Q(abbr=group) |
                    Q(aliases__contains=[group])
                )
            )

            # If one group found, just set id of that group.
            if len(found) == 1:
                post['group'] = found[0].pk

            # If more than one group found, return back to form and ask to
            # select which group.
            elif len(found) > 1:
                names = [p.name for p in found]
                names = suggested_person_or_group_for_quote(names)
                form = AddQuoteForm(post)
                return TemplateResponse(request, 'add_quote.html', {
                    'form': form,
                    'names': names,
                    'source': post.get('source'),
                })

            # If group is not found, save Quote and proceed to the next Add
            # Group form.
            else:
                post['group'] = ''

        form = AddQuoteForm(post)
        if form.is_valid():
            voter: Voter = request.voter
            quote: Quote = form.save(commit=False)
            quote.private_key = voter.private_key
            quote.active = False
            quote.save()

            # Add new person.
            if author_type == 'person':
                if quote.person is None:
                    params = {'quote': quote.pk}
                    if person:
                        params['person'] = person
                    return HttpResponseRedirect(
                        reverse('add-person') + '?' + urlencode(params)
                    )

            # Add new group.
            else:
                if quote.group is None:
                    params = {'quote': quote.pk}
                    if group:
                        params['group'] = group
                    return HttpResponseRedirect(
                        reverse('add-group') + '?' + urlencode(params)
                    )

            return HttpResponseRedirect(quote.get_absolute_url())

        else:
            source = post.get('source')
            data = extract_source_data(source)
            names = suggested_person_or_group_for_quote(data['names'])
            return TemplateResponse(request, 'add_quote.html', {
                'form': form,
                'names': names,
                'source': source,
            })


@require_http_methods(['GET', 'POST'])
def add_person(request: HttpRequest):
    voter: Voter = request.voter
    quote: Optional[Quote] = None
    if 'quote' in request.GET:
        quote = get_object_or_404(
            Quote,
            pk=request.GET['quote'],
            private_key=voter.private_key,
        )

    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            person = form.save(commit=False)
            person.slug = slugify(person.name)[:50]
            person.save()
            if quote:
                quote.person = person
                quote.group = None
                quote.save()
                return HttpResponseRedirect(quote.get_absolute_url())
            else:
                return HttpResponseRedirect(reverse('home'))
    else:
        form = PersonForm(initial={
            'name': request.GET.get('person', ''),
        })
    return TemplateResponse(request, 'add_person.html', {
        'form': form,
    })


@require_http_methods(['GET', 'POST'])
def add_group(request: HttpRequest):
    voter: Voter = request.voter
    quote: Optional[Quote] = None
    if 'quote' in request.GET:
        quote = get_object_or_404(
            Quote,
            pk=request.GET['quote'],
            private_key=voter.private_key,
        )

    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.slug = slugify(group.name)[:50]
            group.save()
            if quote:
                quote.person = None
                quote.group = group
                quote.save()

rinkimai/templates/add_group.html
{% extends "base.html" %}

{% block title %}Rinkimai{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <p><input type="submit" value="Pateikti"></p>
    </form>
{% endblock %}

rinkimai/templates/add_person.html
{% extends "base.html" %}

{% block title %}Rinkimai{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <p><input type="submit" value="Pateikti"></p>
    </form>
{% endblock %}

rinkimai/templates/add_quote.html
{% extends "base.html" %}

{% block title %}Rinkimai{% endblock %}

{% block body %}
<h1>Nauja citata</h1>
<form method="post">
    {% csrf_token %}

    <p><strong>Citatos šaltinis:</strong></p>
    <p>
        <a href="{{ source }}" target="_blank">{{ source }}</a>
        <input type="hidden" name="source" value="{{ source }}">
    </p>

    <p><label for="id_person"><strong>Citatos autorius</strong></label></p>
    <p><small>Vardas Pavardė arba partijos pavadinimas.</small></p>
    {% if names %}
        <p><small>
            Pasirinkite vieną iš sąrašo arba įrašykite citatos autorių žemiau.
        </small></p>
        {% for name in names %}
            <p>
                <input type="radio" id="suggested_author_{{ forloop.counter }}"
                       name="suggested_author" value="{{ name.type }}:{{ name.id }}">
                <label for="suggested_author_{{ forloop.counter }}">
                    {{ name.label }}</label>
            </p>
        {% endfor %}
    {% endif %}
    <p>
        <input type="radio" name="suggested_author" value="person">
        <input type="text" id="id_person" name="person" placeholder="Vardas Pavardė">
        (asmuo)
    </p>
    <p>
        <input type="radio" name="suggested_author" value="group">
        <input type="text" id="id_group" name="group" placeholder="Pavadinimas">
        (partija)
    </p>

    <p><label for="{{ form.date.id_for_label }}"><strong>Citatos data</strong>:</label></p>
    <p>{{ form.date }}</p>

    <p><label for="{{ form.text.id_for_label }}"><strong>Citata</strong>:</label></p>
    <p>{{ form.text }}</p>

    <p><label for="{{ form.tags.id_for_label }}"><strong>Žymės</strong>:</label></p>
    <p>
        {{ form.tags }}
    </p>
    <p><small>Apie ką ši citata?</small></p>
    <p><small>Žymių sąrašas atskirtas kableliais.</small></p>

    <hr>
    <p><input type="submit" value="Pateikti"></p>
</form>
{% endblock %}

rinkimai/templates/ask_quote_source.html
{% extends "base.html" %}

{% block title %}Rinkimai{% endblock %}

{% block body %}
<p>Pateikite šaltinio nuorodą:</p>
<form method="get">
    {{ form }}
    {% if person %}
        <input type="hidden" name="person" value="{{ person }}">
    {% endif %}
    {% if group %}
        <input type="hidden" name="group" value="{{ group }}">
    {% endif %}
    <input type="submit" value="Pateikti">
</form>
{% endblock %}

rinkimai/templates/base.html
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        .reaction-like {
            color: limegreen;
        }
        .reaction-dislike {
            color: indianred;
        }
        .reaction-ignore {
            color: gray;
        }

        /* Voter candidate table. */
        #voter-candidates-table > tbody > tr > td:last-child {
            text-align: right;
        }

    </style>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        function save_reaction($this, quote, reaction) {
            let data = {
                quote: quote,
                reaction: reaction
            };
            $.post("{% url 'save-reaction' %}", data, function (data) {
                // Clean previous state
                $this.parent('span').find('button').removeClass([
                    "reaction-like",
                    "reaction-dislike",
                    "reaction-ignore",
                ]);
                $this.parent('span').find('button').removeAttr('disabled');

                // Update given button
                if (reaction > 0) {
                    $this.addClass("reaction-like");
                } else if (reaction < 0) {
                    $this.addClass("reaction-dislike");
                } else {
                    $this.addClass("reaction-ignore");
                }
                $this.attr("disabled", true);
            });
        }
    </script>
    {% if user.is_staff %}
        <script>
        function approve_quote($this, quote, active) {
            let data = {
                quote: quote,
                active: active,
            };
            $this.parent('span').find('button').removeAttr('disabled');
            $.post("{% url 'approve-quote' %}", data, function (data) {
                $this.parent('span').find('button').toggle();
            });
        }
        </script>
    {% endif %}
</head>
<body>
    <div>
        Rinkimai:
        <strong>
            {% if election %}
                {{ election }}
            {% else %}
                &lt;No selected&gt;
            {% endif %}
        </strong>
    </div>
    <div>
        <p>Meniu:</p>
        <ul>
            {% for item in menu %}
                {% if item.staff is False or user.is_staff %}
                    {% if item.name == active_menu_item %}
                        <li><strong>{{ item.title }}</strong></li>
                    {% else %}
                        <li><a href="{{ item.url }}">{{ item.title }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    </div>

    {% block body %}
    {% endblock %}
</body>
</html>

rinkimai/templates/group_quotes.html
{% extends "quotes.html" %}

rinkimai/templates/index.html
{% extends "quotes.html" %}

{% block title %}Rinkimai{% endblock %}

rinkimai/templates/person_quotes.html
{% extends "quotes.html" %}

rinkimai/templates/quote_details.html
{% extends "quotes.html" %}

rinkimai/templates/quotes.html
{% extends "base.html" %}

{% block body %}
    <a href="{{ add_new_quote_url }}">Add new quote</a>

    {% for quote in quotes %}
        <div>
            <hr>
            <p>
                {% if quote.person %}
                    <a href="{% url "person-quotes" quote.person.slug %}"
                        >{{ quote.person.name }}</a>
                {% else %}
                    <a href="{% url "group-quotes" quote.group.slug %}"
                        >{{ quote.group.name }}</a>
                {% endif %}
                (<a href="{{ quote.source.url }}" target="_blank">{{ quote.source.name }}</a>,
                {{ quote.date }})
                |
                <span>
                    <button
                        id="reaction-like"
                        onclick="save_reaction($(this), '{{ quote.id }}', 1);"
                        {% if quote.reaction > 0 %}
                        class="reaction-like"
                        disabled
                        {% endif %}
                        >Patinka</button>
                    <button
                        id="reaction-dislike"
                        onclick="save_reaction($(this), '{{ quote.id }}', -1);"
                        {% if quote.reaction < 0 %}
                        class="reaction-dislike"
                        disabled
                        {% endif %}
                        >Nepatinka</button>
                    |
                    <button
                        id="reaction-ignore"
                        onclick="save_reaction($(this), '{{ quote.id }}', 0);"
                        {% if quote.reaction is 0 %}
                        class="reaction-ignore"
                        disabled
                        {% endif %}
                        >Neįdomu</button>
                </span>

                {% if user.is_staff %}
                    |
                    <span>
                        <button
                            {% if not quote.active %}style="display: none;"{% endif %}
                            onclick="approve_quote($(this), '{{ quote.id }}', false);"
                            >Slėpti</button>
                        <button
                            {% if quote.active %}style="display: none;"{% endif %}
                            onclick="approve_quote($(this), '{{ quote.id }}', true);"
                            >Rodyti</button>
                    </span>
                    |
                    <a href="{% url 'admin:rinkimai_quote_change' quote.id %}" target="_blank">
                        change
                    </a>
                {% endif %}
            </p>
            <p>{{ quote.text }}</p>
            <p>
                {% if quote.tags %}
                    Žymės:
                    {% for tag in quote.tags %}
                        <a href="{% url 'tag-quotes' tag %}">{{ tag }}</a>{% if not forloop.last %}, {% else %}.{% endif %}
                    {% endfor %}
                {% endif %}

            </p>
        </div>
    {% endfor %}

{% endblock %}

rinkimai/templates/reactions.html
{% extends "quotes.html" %}

rinkimai/templates/tag_quotes.html
{% extends "quotes.html" %}

rinkimai/templates/voter-candidates.html
{% extends "base.html" %}

{% block body %}
    <a href="{{ add_new_quote_url }}">Add new quote</a>

    <h1>Mano kandidatai</h1>

    <table id="voter-candidates-table">
        <thead>
        <tr>
            <th>Kandidatas</th>
            <th>Reitingas</th>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
            <tr>
                <td>
                    {% if candidate.party %}
                    <a href="{% url 'group-quotes' candidate.party.slug %}">{{ candidate.party.abbr }}</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'person-quotes' candidate.slug %}">{{ candidate.name }}</a>
                </td>
                <td>{{ candidate.rating }}%</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}